services:
  gateway-app:
    container_name: notification-app
    build:
      context: .
      dockerfile: Dockerfile
    expose :
      - 8000
    networks:
      - my-network

networks:
  my-network:
    external: true

